## Intro to Pandas

Slide 61

Things you can do with pandas package:

Data Manipulation
- Loading and cleaning data
- Filtering, sorting
- Access specific columns or rows
- Rolling metrics - moving average
- Calculate new columns --> formulas to do math
- Pivot table

In [27]:
# Importing pandas
import pandas as pd  
pd.__version__

# pd is the common "alias" used in Python community
# http://pandas.pydata.org/pandas-docs/stable/

'3.0.3'

#### Importing data
Slide 64

In [31]:
sp500 = pd.read_csv("StockData/sp500.csv") #using relative path of project
dir(sp500) # lists out all properties and methods

# Can also use an absolute path:
# Here the r means raw, so \ will not be interpreted as an encoding
aapl = pd.read_csv(r"C:\pydata\aapl.csv") # MAKE SURE THIS FILE EXISTS <<<<<<<<<<<
# note you have to use r at the beginning of the string if using backslashes (Windows)

# To see a summary of the data use .info
sp500.info() # summary of all columns NB Date is currently string format
# summaryStats = sp500.describe()
summaryStats

# To look at the first and last 5 rows:
sp500.head()
sp500.tail()

# Display more or less columns in the output
pd.set_option("display.max_columns", 10) # or 3
sp500

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1260 non-null   str
 1   Open       1260 non-null   float64
 2   High       1260 non-null   float64
 3   Low        1260 non-null   float64
 4   Close      1260 non-null   float64
 5   Adj Close  1260 non-null   float64
 6   Volume     1260 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 78.0 KB

,Date,Open,High,Low,Close,Adj Close,Volume
0,9/30/13,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,10/01/13,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,10/02/13,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,10/03/13,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,10/04/13,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,9/24/18,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,9/25/18,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,9/26/18,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,9/27/18,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,9/28/18,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

#### Setting up the Data

In [84]:
#Change Dates to be numbers not text
# NB we will get a warning about date format here
sp500['Date'] = pd.to_datetime(sp500['Date'], format="%m/%d/%y") # make sure this matches the incoming dat format
sp500.info() #Date column is now datetime not object

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1260 non-null   datetime64[us]
 1   Open       1260 non-null   float64
 2   High       1260 non-null   float64
 3   Low        1260 non-null   float64
 4   Close      1260 non-null   float64
 5   Adj Close  1260 non-null   float64
 6   Volume     1260 non-null   int64
 7   Ticker     1260 non-null   str
dtypes: datetime64[us](1), float64(5), int64(1), str(1)
memory usage: 85.2 KB

In [33]:
#changing the index to Dates column
sp500.set_index(['Date'], drop=True, inplace = True)
    #inplace = True is the same thing as sp500 = sp500.set_index....
    #most pandas functions/methods don't change the original table
    #you need to reassign to change the original DataFrame
    #or use inplace=True
sp500

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

### Exercise
Try Exercise 1 from Assignment 2

### Accessing/Slicing Data
Slides 72-76

#### Accessing rows

#### Method 1 - iloc - integer location - index

In [41]:
#starts with 0; row 1 in Excel = row 0 in Pandas

sp500.iloc[0] #first row
# pd.options.display.float_format = '{:.2f}'.format #to change format of floats

sp500.iloc[:2]#start at beg, stop row[1]
# #still does open interval for iloc

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000

#### Method 2 - loc - new index, which is now Date

In [42]:
sp500.loc['20130930']
sp500.loc['20130930':'20131010'] #inclusive of the last date
sp500.loc['2013-10'] #prints all October of 2013
sp500.loc['2016'] #all 2016

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2016-01-04,2038.199951,2038.199951,1989.680054,2012.660034,2012.660034,4304880000
2016-01-05,2013.780029,2021.939941,2004.170044,2016.709961,2016.709961,3706620000
2016-01-06,2011.709961,2011.709961,1979.050049,1990.260010,1990.260010,4336660000
2016-01-07,1985.319946,1985.319946,1938.829956,1943.089966,1943.089966,5076590000
2016-01-08,1945.969971,1960.400024,1918.459961,1922.030029,1922.030029,4664940000
...,...,...,...,...,...,...
2016-12-23,2260.250000,2263.790039,2258.840088,2263.790039,2263.790039,2020550000
2016-12-27,2266.229980,2273.820068,2266.149902,2268.879883,2268.879883,1987080000
2016-12-28,2270.229980,2271.310059,2249.110107,2249.919922,2249.919922,2392360000
2016-12-29,2249.500000,2254.510010,2244.560059,2249.260010,2249.260010,2336370000
2016-12-30,2251.610107,2253.580078,2233.620117,2238.830078,2238.830078,2670900000

### Accessing columns

#### Method 1 - Using df['name column'], similar to Dictionaries

In [43]:
sp500['Adj Close']

Date
2013-09-30    1681.550049
2013-10-01    1695.000000
2013-10-02    1693.869995
2013-10-03    1678.660034
2013-10-04    1690.500000
                 ...
2018-09-24    2919.370117
2018-09-25    2915.560059
2018-09-26    2905.969971
2018-09-27    2914.000000
2018-09-28    2913.979980
Name: Adj Close, Length: 1260, dtype: float64

#### Method 2 - Using df.colName, does not work for columns with spaces in name

In [40]:
sp500.Close

Date
2013-09-30    1681.550049
2013-10-01    1695.000000
2013-10-02    1693.869995
2013-10-03    1678.660034
2013-10-04    1690.500000
                 ...
2018-09-24    2919.370117
2018-09-25    2915.560059
2018-09-26    2905.969971
2018-09-27    2914.000000
2018-09-28    2913.979980
Name: Close, Length: 1260, dtype: float64

### Slicing parts of DataFrame

#### Method 1 - Using .loc['rowName','colName']

In [45]:
sp500.loc['2014-09', 'Low'] #column name inside []
sp500.loc['2015-09', ['Low','High']] #multiple columns can be given in a list

                    Low         High
Date
2015-09-01  1903.069946  1970.089966
2015-09-02  1916.520020  1948.910034
2015-09-03  1944.719971  1975.010010
2015-09-04  1911.209961  1947.760010
2015-09-08  1927.300049  1970.420044
2015-09-09  1937.880005  1988.630005
2015-09-10  1937.189941  1965.290039
2015-09-11  1939.189941  1961.050049
2015-09-14  1948.270020  1963.060059
2015-09-15  1954.300049  1983.189941
2015-09-16  1977.930054  1997.260010
2015-09-17  1986.729980  2020.859985
2015-09-18  1953.449951  1989.660034
2015-09-21  1955.800049  1979.640015
2015-09-22  1929.219971  1961.390015
2015-09-23  1932.569946  1949.520020
2015-09-24  1908.920044  1937.170044
2015-09-25  1921.500000  1952.890015
2015-09-28  1879.209961  1929.180054
2015-09-29  1871.910034  1899.479980
2015-09-30  1887.140015  1920.530029

#### Method 2 - Using .loc['rowName']['colName']

In [49]:
sp500.loc['2016-01']['Volume']#column name inside []
    #Careful when using this method to "Copy" data into another DataFrame
    #It could create a "view" instead of a copy, where tables are linked
    #Use df.loc['row']['col].copy() or Method 1
    #See Slide 72 for more details

sp500_OC = sp500[['Open','Close']]
sp500_HL = sp500.loc[:,['High','Low']] #another way of copying just values
        # .loc[:] grabs all rows
sp500_HL

                   High          Low
Date
2013-09-30  1687.260010  1674.989990
2013-10-01  1696.550049  1682.069946
2013-10-02  1693.869995  1680.339966
2013-10-03  1692.349976  1670.359985
2013-10-04  1691.939941  1677.329956
...                 ...          ...
2018-09-24  2923.790039  2912.629883
2018-09-25  2923.949951  2913.699951
2018-09-26  2931.149902  2903.280029
2018-09-27  2927.219971  2909.270020
2018-09-28  2920.530029  2907.500000

[1260 rows x 2 columns]

#### Output to Excel

In [50]:
# NB make sure 'output' folder already exists
sp500_OC.to_csv("Output/SP500 Open Close.csv")
sp500_HL.to_excel("Output/SP500 High Low.xlsx")

### Manipulating Data
#### Sorting, Filtering and Creating new columns & calculated fields

#### Sorting Data
Slide 70

In [55]:
#Descending by volume
sp500.sort_values(['Volume'], ascending=False, inplace=True)
#don't forget the inplace=True if you want to change the original
#OR: sp500 = sp500.sort_values....
sp500

#Sort multiple cols
sp500.sort_values(['Volume','Close','Open'],
                  ascending=[False,False,True],
                  inplace=True)
sp500

#Sort by Index
sp500.sort_index(inplace=True)
sp500 # back to where we started

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

#### Filtering Data
Slide 75

In [56]:
# posDays = sp500[ booleanMask  ]
#where a boolean mask is a column of True/False

#Filter the table for positive days
    #Today's close > Today's open
sp500[sp500['Open'] < sp500['Close']] #method 1 - use condition directly
# sp500[sp500['isPositive']] #method 2 - give it a column of T/F (we do not have this column available yet)

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
2013-10-10,1660.880005,1692.560059,1660.880005,1692.560059,1692.560059,3362300000
2013-10-11,1691.089966,1703.439941,1688.520020,1703.199951,1703.199951,2944670000
...,...,...,...,...,...,...
2018-09-18,2890.739990,2911.169922,2890.429932,2904.310059,2904.310059,3074610000
2018-09-19,2906.600098,2912.360107,2903.820068,2907.949951,2907.949951,3280020000
2018-09-20,2919.729980,2934.800049,2919.729980,2930.750000,2930.750000,3337730000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

#### More complex filtering:

In [61]:
#Volume is bw x and y shares

sp500[ (sp500['Volume'] >= 1.30e+09) & (sp500['Volume'] <= 3.5e+09) ]
# 1,300,000,000 - 3,500,000,000
# filteredTable = sp500[(sp500['Volume'] >= 1.30e+09) & (sp500['Volume'] <= 3.5e+09)]
    #Careful! filteredTable is linked to sp500
    #if you change the value of one of the rows
    #it changes the value in the bigger table
# filteredTable

#If you don't want that, use .copy()
# filteredDF = sp500[sp500['Close'] < sp500['Open']].copy()
# filteredDF

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [65]:
#See slide 76
sp500['isPositive'] = sp500['Close'].shift(1) < sp500['Close']
#today's close price is > row above close price (prev day)
sp500

# sp500['priceScaled'] = sp500['Close'] * 100
# sp500
#Index Price > 2,100 and <2,200
# sp500[(sp500['Close'] > 2100) & (sp500['Close'] < 2200)]

,Open,High,Low,Close,Adj Close,Volume,isPositive,priceScaled
Date,,,,,,,,
2015-02-17,2096.469971,2101.300049,2089.800049,2100.340088,2100.340088,3361750000,True,210034.0088
2015-02-20,2097.649902,2110.610107,2085.439941,2110.300049,2110.300049,3281600000,True,211030.0049
2015-02-23,2109.830078,2110.050049,2103.000000,2109.659912,2109.659912,3093680000,False,210965.9912
2015-02-24,2109.100098,2117.939941,2105.870117,2115.479980,2115.479980,3199840000,True,211547.9980
2015-02-25,2115.300049,2119.590088,2109.889893,2113.860107,2113.860107,3312340000,False,211386.0107
...,...,...,...,...,...,...,...,...
2016-11-18,2186.850098,2189.889893,2180.379883,2181.899902,2181.899902,3572400000,False,218189.9902
2016-11-21,2186.429932,2198.699951,2186.429932,2198.179932,2198.179932,3607010000,True,219817.9932
2016-11-30,2204.969971,2214.100098,2198.810059,2198.810059,2198.810059,5533980000,False,219881.0059
2016-12-01,2200.169922,2202.600098,2187.439941,2191.080078,2191.080078,5063740000,False,219108.0078
2016-12-02,2191.120117,2197.949951,2188.370117,2191.949951,2191.949951,3779500000,True,219194.9951

#### Calculated Fields

In [66]:
import numpy as np
sp500['logClose'] = np.log(sp500['Close'])
sp500['logReturns'] = sp500['logClose'].diff() #default takes previous row
sp500

,Open,High,Low,Close,Adj Close,Volume,isPositive,priceScaled,logClose,logReturns
Date,,,,,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000,False,168155.0049,7.427471,NaN
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000,True,169500.0000,7.435438,0.007967
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000,False,169386.9995,7.434771,-0.000667
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000,False,167866.0034,7.425751,-0.009020
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000,True,169050.0000,7.432780,0.007028
...,...,...,...,...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000,False,291937.0117,7.979123,-0.003522
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000,False,291556.0059,7.977817,-0.001306
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000,False,290596.9971,7.974523,-0.003295
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000,True,291400.0000,7.977282,0.002759
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000,False,291397.9980,7.977275,-0.000007

In [68]:
#Moving Averages
#1-Day moving average --> equal to yesterday
sp500['ma_1'] = sp500['Close'].shift(1)
sp500['ma_5'] = sp500['ma_1'].rolling(window = 5, min_periods = 5).mean()
sp500['ma_20'] = sp500['ma_1'].rolling(window = 20, min_periods = 20).mean()
sp500

,Open,High,Low,Close,Adj Close,...,logClose,logReturns,ma_1,ma_5,ma_20
Date,,,,,,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,...,7.427471,NaN,NaN,NaN,NaN
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,...,7.435438,0.007967,1681.550049,NaN,NaN
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,...,7.434771,-0.000667,1695.000000,NaN,NaN
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,...,7.425751,-0.009020,1693.869995,NaN,NaN
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,...,7.432780,0.007028,1678.660034,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,...,7.979123,-0.003522,2929.669922,2912.295996,2897.263477
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,...,7.977817,-0.001306,2919.370117,2918.410010,2899.497486
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,...,7.974523,-0.003295,2915.560059,2920.660010,2900.438489
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,...,7.977282,0.002759,2905.969971,2920.264014,2900.860986
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,...,7.977275,-0.000007,2914.000000,2916.914014,2900.858985

In [36]:
#for more complex formulas use .apply()
#Slide 80

### Resampling Data --> Daily to Monthly
Slide 79

In [69]:
#Step 1 - Dictionary with Rules for each Column
rules = {'Open':'first', 'Close':'last','Volume':'sum'}
monthlySP500 = sp500.resample('ME').agg(rules) # ME for month-end
monthlySP500

                   Open        Close       Volume
Date
2013-09-30  1687.260010  1681.550049   3308630000
2013-10-31  1682.410034  1756.540039  76647400000
2013-11-30  1758.699951  1805.810059  63628190000
2013-12-31  1806.550049  1848.359985  64958820000
2014-01-31  1845.859985  1782.589966  75871910000
...                 ...          ...          ...
2018-05-31  2642.959961  2705.270020  75617280000
2018-06-30  2718.699951  2718.370117  77439710000
2018-07-31  2704.949951  2816.290039  64542170000
2018-08-31  2821.169922  2901.520020  69238220000
2018-09-30  2896.959961  2913.979980  62492080000

[61 rows x 3 columns]

#### Merging Data Sets
Slides 85 - 95

In [72]:
#Concat --> columns have to match up
aapl = pd.read_csv("StockData/aapl.csv")
sp500 = pd.read_csv("StockData/sp500.csv")

aapl['Ticker'] = "AAPL"
sp500['Ticker'] = 'SP500'

aapl
sp500

concatData = pd.concat([aapl,sp500])
#header names were the same
concatData

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,10/01/13,68.349998,69.877144,68.339996,69.708572,63.523125,88470900,AAPL
1,10/02/13,69.375717,70.257141,69.107140,69.937141,63.731426,72296000,AAPL
2,10/03/13,70.072861,70.335716,68.677139,69.058571,62.930801,80688300,AAPL
3,10/04/13,69.122856,69.228569,68.371429,69.004288,62.881340,64717100,AAPL
4,10/07/13,69.508568,70.378571,69.335716,69.678574,63.495800,78073100,AAPL
...,...,...,...,...,...,...,...,...
1255,9/24/18,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000,SP500
1256,9/25/18,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000,SP500
1257,9/26/18,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000,SP500
1258,9/27/18,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000,SP500
1259,9/28/18,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000,SP500

In [81]:
#Merge --> you can pick one or more columns to merge on
mergedData = sp500.merge(aapl)
    #merge on all the columns that have the same name
    #getting no results
mergedData
    
# mergedData = sp500.merge(aapl, left_on=['Date'], right_on=['Date'])
                #left table: sp500
                #right table: aapl
                #put _x, _y as suffixed to header names
mergedData

mergedData = sp500.merge(aapl, left_on=['Date'], right_on=['Date'], suffixes=("_sp500","_aapl"))
mergedData

#default how="inner"
mergedData = sp500.merge(aapl, how="left", left_on=['Date'], right_on=['Date'], suffixes=("_sp500","_aapl"))
mergedData

,Date,Open_sp500,High_sp500,Low_sp500,Close_sp500,...,Low_aapl,Close_aapl,Adj Close_aapl,Volume_aapl,Ticker_aapl
0,9/30/13,1687.260010,1687.260010,1674.989990,1681.550049,...,NaN,NaN,NaN,NaN,NaN
1,10/01/13,1682.410034,1696.550049,1682.069946,1695.000000,...,68.339996,69.708572,63.523125,88470900.0,AAPL
2,10/02/13,1691.900024,1693.869995,1680.339966,1693.869995,...,69.107140,69.937141,63.731426,72296000.0,AAPL
3,10/03/13,1692.349976,1692.349976,1670.359985,1678.660034,...,68.677139,69.058571,62.930801,80688300.0,AAPL
4,10/04/13,1678.790039,1691.939941,1677.329956,1690.500000,...,68.371429,69.004288,62.881340,64717100.0,AAPL
...,...,...,...,...,...,...,...,...,...,...,...
1255,9/24/18,2921.830078,2923.790039,2912.629883,2919.370117,...,216.630005,220.789993,220.789993,27693400.0,AAPL
1256,9/25/18,2921.750000,2923.949951,2913.699951,2915.560059,...,219.699997,222.190002,222.190002,24554400.0,AAPL
1257,9/26/18,2916.979980,2931.149902,2903.280029,2905.969971,...,219.759995,220.419998,220.419998,23984700.0,AAPL
1258,9/27/18,2911.649902,2927.219971,2909.270020,2914.000000,...,223.539993,224.949997,224.949997,30181200.0,AAPL
1259,9/28/18,2910.030029,2920.530029,2907.500000,2913.979980,...,224.020004,225.740005,225.740005,22889300.0,AAPL

### Exercises
Try exercises 2, 3 and 4 from assignment 2

If time , try exercises 5, 6 & 7 from assignment 2